pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
    stage('DB') {
      agent {
        docker { 
          image 'mysql:latest'
          args '-e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE=testdb'
        }
      }
      steps {
        sh '''
          # Wait for MySQL to start and check version
          sleep 10
          mysql --version
          echo "MySQL container is running successfully!"
        '''
      }
    }
  }
}
